### ISSUE TITLE
Headings on about us page are inconsistently centered

### ISSUE THREAD

**Issue by michalbednarski** [MADWI/AppWIZUT2#17]
When text is wrapped on about us page, the field in which it was gets centered

![screenshot_2015-12-10-22-07-03](https://cloud.githubusercontent.com/assets/1826899/11728552/d64811c8-9f8a-11e5-965c-e47c53c9bca0.png)

**Comment by dawhey** [comment]
Issue closed by commit 64730c93ed7e2aec938ed074abb1c1efa3c9adaf (message: "about_us_layout minor fixes + hyperlinks added")
