### ISSUE TITLE
Calendar doesn't show event indicator lines on first open

### ISSUE THREAD

**Issue by michalbednarski** [MADWI/AppWIZUT2#19]
1. Clear application data (through settings or `adb shell pm clear pl.edu.zut.mad.appwizut2`)
2. Open calendar

The lines indicating how many events we have on that day won't show up

**Comment by mjozwk** [comment]
For me they how up :o


2015-12-12 13:17 GMT+01:00 michalbednarski <notifications@github.com>:

**Comment by mjozwk** [comment]
For me they show up :o

2015-12-12 13:17 GMT+01:00 michalbednarski notifications@github.com:

**Comment by michalbednarski** [comment]
Right, they are okay on master, this is regression on Calendar branch, specifically commit e55ae71c47718d758153673bbc0a08bfbd0f782e
